version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - errcheck
    - errname
    - gocritic
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - ireturn
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - reassign
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
