image: dkolaska/blackjack-ci:0.0.3

stages:
  - test

test:
  stage: test
  script:
    - make proto
    - cd ./bjack-api
    - go fmt ./...
    - golangci-lint run
    - go test ./...
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
