name: Blackjack integration workflow

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3
        with:
          just-version: 1.55.0

      - name: Validate API
        run: |
          just build_api_image

