name: Blackjack integration workflow

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: dkolaska/blackjack-ci:0.0.3
    steps:
      - uses: actions/checkout@v4

      - name: Generate protobuf files
        run: make proto

      - name: Format
        run: test -z $(gofmt -l .) || gofmt -l . | false
      
      - name: Lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: v1.62.2
          working-directory: ./bjack-api
        env:
          GOFLAGS: -buildvcs=false
      
      - name: Test
        run: make test
