name: Blackjack integration workflow

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: golang:1.26.4-alpine3.24
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        run: |
          apk update
          apk add just npm
          just setup
          just test
          just fmt
          just lint

